### ISSUE TITLE
[EPIC] Performance Improvements

### ISSUE THREAD

**Issue by Fulviuus** [dusk-network/web-wallet#907]
# Epic

## Summary

This Epic will be a collection of fixes required to address the various performance issues currently afflicting the first release of the Web Wallet.

The two major areas of performance improvements we can work on are the `synchronization` with the node, and the `WebAssembly` execution.

## Tasks

- [x] dusk-network/exu#1
- [x] dusk-network/dusk-wallet-js#11
- [x] dusk-network/web-wallet#902 
- [x] https://github.com/dusk-network/exu/issues/3
